//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Alembic.rc
//
#define IDC_TETRA                       0
#define IDC_OCTA                        1
#define IDC_ICOSA                       2
#define IDD_FORMVIEW                    101
#define IDD_ALEMBIC_EXPORT_DLG          101
#define IDD_TO_POLY                     102
#define IDD_TO_MESH                     103
#define IDC_MAX_SIZESPIN                103
#define IDD_TO_PATCH                    104
#define IDC_MAX_SIZE                    104
#define IDC_THRESHSPIN                  105
#define IDD_ALEMBIC_ID_PARAMS           105
#define IDC_THRESH                      106
#define IDS_ABC_FILE_TYPE               106
#define IDD_ALEMBIC_PROPS               106
#define IDS_OPEN_ABC_CAPTION            107
#define IDS_ABC_ID                      108
#define IDS_PREVIEW                     109
#define IDS_RENDER                      110
#define IDS_PROPS                       111
#define IDS_MUTED                       112
#define IDS_TIME                        113
#define IDS_ALEMBIC                     114
#define IDS_GEOALPHA                    115
#define IDS_CAMERA                      116
#define IDS_ADDITIVE                    117
#define IDS_IGNORE_SUBFRAME_SAMPLES     118
#define IDS_RENDER_AS_TICKS             119
#define IDS_VIEWPORT_PERCENT            120
#define IDD_GSPHERE1                    179
#define IDD_GSPHERE2                    180
#define IDD_GSPHERE3                    181
#define IDC_RADIUS                      1000
#define IDC_BUTTON1                     1001
#define IDC_OK                          1001
#define IDC_SEGMENTS                    1001
#define IDC_BUTTON2                     1002
#define IDC_CANCEL                      1002
#define IDC_CREATEDIAMETER              1002
#define IDC_COMBO1                      1003
#define IDC_COMBO_MESH                  1003
#define IDC_CREATERADIUS                1003
#define IDC_CHECK1                      1004
#define IDC_CHECK_BINDPOSE              1004
#define IDC_SEGSPINNER                  1004
#define IDC_CHECK_VISIBILITY            1004
#define IDC_CHECK_MUTED                 1004
#define IDC_IGNORE_SUBFRAME_SAMPLES     1004
#define IDC_ADDITIVE_CHECKBOX           1004
#define IDC_RENDER_AS_TICKS_CHECKBOX    1004
#define IDC_CHECK2                      1005
#define IDC_CHECK_UV                    1005
#define IDC_RADSPINNER                  1005
#define IDC_CHECK3                      1006
#define IDC_CHECK_CLUSTER               1006
#define IDC_OBSMOOTH                    1006
#define IDC_UVS_CHECKBOX                1006
#define IDC_CHECK4                      1007
#define IDC_CHECK_TOPO                  1007
#define IDC_EDIT1                       1008
#define IDC_EDIT_IN                     1008
#define IDC_ABC_OBJECTID                1008
#define IDC_EDIT2                       1009
#define IDC_EDIT_OUT                    1009
#define IDC_ABC_ARCHIVE                 1009
#define IDC_EDIT3                       1010
#define IDC_EDIT_FRAME_STEP             1010
#define IDC_EDIT4                       1011
#define IDC_EDIT_SUB_STEP               1011
#define IDC_CUSTOM3                     1015
#define IDC_EDIT_TIME                   1015
#define IDC_CUSTOM4                     1016
#define IDC_SPIN_TIME                   1016
#define IDC_EDIT_TIME_OFFSET            1017
#define IDC_SPIN_TIME_OFFSET            1018
#define IDC_EDIT_SCALE                  1019
#define IDC_EDIT_TIME_SCALE             1019
#define IDC_TIME_EDIT                   1019
#define IDC_SPIN_TIME_SCALE             1020
#define IDC_TIME_SPINNER                1020
#define IDC_TIME_SPIN                   1020
#define IDC_MUTED_CHECKBOX              1021
#define IDC_TOPOLOGY_CHECKBOX           1022
#define IDC_CAMERA_CHECKBOX             1022
#define IDC_VIEWPORT_PERCENT_SPIN       1022
#define IDC_GEOMETRY_CHECKBOX           1023
#define IDC_NORMALS_CHECKBOX2           1024
#define IDC_NORMALS_CHECKBOX            1024
#define IDC_GEOALPHA_SPIN               1027
#define IDC_GEOALPHA_EDIT               1028
#define IDC_LIMIT_SIZE                  1276
#define IDC_KEEP_CONVEX                 1277
#define IDC_TI_POSX                     3019
#define IDC_TI_POSXSPIN                 3020
#define IDC_TI_POSY                     3021
#define IDC_TI_POSYSPIN                 3022
#define IDC_TI_CREATE                   3023
#define IDC_TI_POSZ                     3024
#define IDC_TI_POSZSPIN                 3025
#define IDC_HEMI                        3071
#define IDC_BASEPIVOT                   3073
#define IDC_MAPPING                     3074
#define IDC_SEL_PRESERVE                3075
#define IDC_SEL_INVERT                  3076
#define IDC_SEL_CLEAR                   3078
#define IDC_SEL_LABEL                   3079
#define IDC_USE_INVIS                   3080
#define IDC_QUADS                       3081
#define IDC_SEL_OBJ                     3082
#define IDC_SEL_VERT                    3083
#define IDC_SEL_EDGE                    3084
#define IDC_SEL_FACE                    3085
#define IDC_SEL_PATCH                   3086
#define IDC_USE_SOFTSEL                 3087
#define IDC_SEL_PIPELINE                3088
#define IDC_ELIMINATE_COLLINEAR         3089
#define IDC_PLANAR                      3147
#define IDS_PARAMS                      4000
#define IDS_PATH                        4001
#define IDS_IDENTIFIER                  4002
#define IDS_TOPOLOGY                    4006
#define IDS_GEOMETRY                    4007
#define IDS_NORMALS                     4008
#define IDS_UVS                         4009
#define IDD_EMPTY                       4011
#define IDS_CAMERATRANSFORM             4012
#define IDS_TIMEOFFSET                  4013
#define IDS_TIMESCALE                   4014
#define IDS_CURRENTTIMEHIDDEN           4015
#define IDS_RB_RADIUS                   30045
#define IDS_RB_SEGS                     30046
#define IDS_RB_POS                      30047
#define IDS_RB_SMOOTH                   30048
#define IDS_RB_PRIMITIVES               30264
#define IDS_GEOSPHERE                   30265
#define IDS_KEYBOARD_ENTRY              30266
#define IDS_CREATION_METHOD             30267
#define IDS_BASETYPE                    30268
#define IDS_LIBDESCRIPTION              30269
#define IDS_PARAMETERS                  30270
#define IDS_HEMI                        30271
#define IDS_ABC_ARCHIVE                 30271
#define IDS_BASEPIVOT                   30272
#define IDS_MAPPING                     30273
#define IDS_SM_NURBS_SURFACE            30274
#define IDS_CT_SURF                     30275
#define IDS_CT_CAP                      30276
#define IDS_GEOSPHERE_CLASS             30277
#define IDS_CONVERT_TO_POLY             30278
#define IDS_KEEP_CONVEX                 30279
#define IDS_LIMIT_SIZE                  30280
#define IDS_MAX_SIZE                    30281
#define IDS_PLANAR                      30282
#define IDS_THRESH                      30283
#define IDS_IGNORE_VIS                  30284
#define IDS_SEL_TYPE                    30285
#define IDS_SEL_LEVEL                   30286
#define IDS_MOD_CATEGORY                30287
#define IDS_CONVERT_TO_PATCH            30288
#define IDS_PATCH_QUADS                 30289
#define IDS_CONVERT_TO_MESH             30290
#define IDS_USE_INVIS                   30291
#define IDS_USE_SOFTSEL                 30292
#define IDS_REMOVE_MID_EDGE_VERTICES    30293
#define IDS_VERTEX                      30294
#define IDS_EDGE                        30295
#define IDS_FACE                        30296
#define IDS_POLYGON                     30297
#define IDS_BORDER                      30298
#define IDS_ELEMENT                     30299
#define IDS_PATCH                       30300
#define IDD_CIRCLEPARAM1                30301
#define IDD_CIRCLEPARAM2                30302
#define IDD_CIRCLEPARAM3                30303
#define IDD_ALEMBIC_MESH_BASE_PARAMS    30304
#define IDD_ALEMBIC_MESH_TOPO_PARAMS    30305
#define IDD_ALEMBIC_MESH_GEOM_PARAMS    30306
#define IDD_ALEMBIC_MESH_BASE_PARAMS3   30307
#define IDD_ALEMBIC_MESH_NORMALS_PARAMS 30307
#define IDD_ALEMBIC_MESH_UVW_PARAMS     30308
#define IDD_ALEMBIC_SPLINE_TOPO_PARAMS  30311
#define IDD_ALEMBIC_SPLINE_GEOM_PARAMS  30312
#define IDD_ALEMBIC_XFORM_PARAMS        30313
#define IDD_ALEMBIC_VISIBILITY_PARAMS   30314
#define IDD_ALEMBIC_PARTICLE_PARAMS     30315
#define IDD_ALEMBIC_FLOAT_CTRL_PARAMS   30316
#define IDD_ALEMBIC_CAMERA_PARAMS       30317
#define IDC_TEXTUREPATH                 40000
#define IDC_PATH_EDIT                   40000
#define IDC_IDENTIFIER_EDIT             40001
#define IDC_PROPERTY_EDIT               40002
#define IDC_VIEWPORT_PERCENT_EDIT       40002
#define IDC_HFOV_EDIT                   40002
#define IDC_VFOV_EDIT                   40003
#define IDC_FOCAL_LENGTH_EDIT           40004
#define IDC_HAPERATURE_EDIT             40005
#define IDC_VAPERATURE_EDIT2            40006
#define IDC_HFILMOFFSET_EDIT            40007
#define IDC_VFILMOFFSET_EDIT            40010
#define IDC_LSRATIO_EDIT                40011
#define IDC_OVERSCANL_EDIT              40012
#define IDC_OVERSCANR_EDIT              40014
#define IDC_OVERSCANT_EDIT              40015
#define IDC_OVERSCANB_EDIT              40016
#define IDC_FSTOP_EDIT                  40017
#define IDC_FOCUSDIST_EDIT              40018
#define IDC_SHUTTEROPEN_EDIT            40019
#define IDC_SHUTTERCLOSE_EDIT           40020
#define IDC_NEARCLIPPINGPLANE_EDIT      40021
#define IDC_SHUTTEROPEN_EDIT2           40022
#define IDC_FAR_CLIPPING_PLANE_EDIT     40022
#define IDC_THRESH_LABEL                65535
#define IDC_MAX_SIZE_LABEL              65535
#define IDC_TIME_LABEL                  65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
