// alembicPlugin
// Initial code generated by Softimage SDK Wizard
// Executed Fri Aug 19 09:14:49 UTC+0200 2011 by helge
//
// Tip: You need to compile the generated code before you can load the plug-in.
// After you compile the plug-in, you can load it by clicking Update All in the
// Plugin Manager.
#include "arnoldHelpers.h"
#include "stdafx.h"

using namespace XSI;
using namespace MATH;

#include "AlembicLicensing.h"

#include "AlembicCurves.h"
#include "AlembicPoints.h"
#include "AlembicWriteJob.h"
#include "CommonMeshUtilities.h"
#include "CommonProfiler.h"
#include "CommonUtilities.h"

ESS_CALLBACK_START(alembic_timecontrol_Define, CRef&)
Context ctxt(in_ctxt);
CustomProperty oCustomProperty;
Parameter oParam;
oCustomProperty = ctxt.GetSource();

// get the current frame in an out
oCustomProperty.AddParameter(L"current", CValue::siFloat,
                             siAnimatable | siPersistable, L"", L"", 0, -100000,
                             100000, -1, 1, oParam);
oCustomProperty.AddParameter(L"factor", CValue::siFloat,
                             siAnimatable | siPersistable, L"", L"", 1, -100000,
                             100000, 0, 2, oParam);
oCustomProperty.AddParameter(L"offset", CValue::siFloat,
                             siAnimatable | siPersistable, L"", L"", 0, -100000,
                             100000, -5, 5, oParam);
oCustomProperty.AddParameter(L"frameOffset", CValue::siFloat,
                             siAnimatable | siPersistable, L"", L"", 0, -100000,
                             100000, -5, 5, oParam);
return CStatus::OK;
ESS_CALLBACK_END

ESS_CALLBACK_START(alembic_timecontrol_DefineLayout, CRef&)
Context ctxt(in_ctxt);
PPGLayout oLayout;
PPGItem oItem;
oLayout = ctxt.GetSource();
oLayout.Clear();
oLayout.AddItem(L"current", L"Current Time");
oLayout.AddItem(L"factor", L"Time Factor");
oLayout.AddItem(L"offset", L"Time Offset");
oLayout.AddItem(L"frameOffset", L"Frame Offset");
return CStatus::OK;
ESS_CALLBACK_END
