#ifndef _FOUNDATION_H_
#define _FOUNDATION_H_

#include "CommonAlembic.h"

#include <xsi_application.h>
#include <xsi_argument.h>
#include <xsi_camera.h>
#include <xsi_cluster.h>
#include <xsi_clusterproperty.h>
#include <xsi_comapihandler.h>
#include <xsi_command.h>
#include <xsi_context.h>
#include <xsi_controlpoint.h>
#include <xsi_customoperator.h>
#include <xsi_customproperty.h>
#include <xsi_dataarray.h>
#include <xsi_dataarray2D.h>
#include <xsi_doublearray.h>
#include <xsi_expression.h>
#include <xsi_facet.h>
#include <xsi_factory.h>
#include <xsi_geometry.h>
#include <xsi_geometryaccessor.h>
#include <xsi_hairprimitive.h>
#include <xsi_iceattribute.h>
#include <xsi_iceattributedataarray.h>
#include <xsi_iceattributedataarray2D.h>
#include <xsi_icecompoundnode.h>
#include <xsi_icenode.h>
#include <xsi_icenodedef.h>
#include <xsi_icenodeinputport.h>
#include <xsi_icetree.h>
#include <xsi_inputport.h>
#include <xsi_kinematics.h>
#include <xsi_kinematicstate.h>
#include <xsi_knot.h>
#include <xsi_material.h>
#include <xsi_materiallibrary.h>
#include <xsi_math.h>
#include <xsi_menu.h>
#include <xsi_model.h>
#include <xsi_null.h>
#include <xsi_nurbscurve.h>
#include <xsi_nurbscurvelist.h>
#include <xsi_nurbssurface.h>
#include <xsi_nurbssurfacemesh.h>
#include <xsi_operator.h>
#include <xsi_operatorcontext.h>
#include <xsi_outputport.h>
#include <xsi_parameter.h>
#include <xsi_pass.h>
#include <xsi_plugin.h>
#include <xsi_pluginregistrar.h>
#include <xsi_point.h>
#include <xsi_polygonface.h>
#include <xsi_polygonmesh.h>
#include <xsi_ppgeventcontext.h>
#include <xsi_ppgitem.h>
#include <xsi_ppglayout.h>
#include <xsi_primitive.h>
#include <xsi_progressbar.h>
#include <xsi_project.h>
#include <xsi_property.h>
#include <xsi_ref.h>
#include <xsi_renderhairaccessor.h>
#include <xsi_sample.h>
#include <xsi_scene.h>
#include <xsi_selection.h>
#include <xsi_shape.h>
#include <xsi_shapekey.h>
#include <xsi_status.h>
#include <xsi_time.h>
#include <xsi_uitoolkit.h>
#include <xsi_utils.h>
#include <xsi_value.h>
#include <xsi_vertex.h>
#include <xsi_x3dobject.h>

#include "AlembicArchiveStorage.h"
#include "Utility.h"

#endif  // _FOUNDATION_H_
